# Gitlab servers' CI/CD instructions for vcst.
#
# ## templates for gitlab-ci.yml
#
# See CI/CD template Development guide at: https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml
#
# This file was forked from
# - https://gitlab.com/gitlab-org/gitlab/-/blob/aaf4d592f405fafd3f50a5e3da69db3703457360/lib/gitlab/ci/templates/Rust.gitlab-ci.yml
# - pointed to from https://docs.gitlab.com/ee/ci/examples
#
# ## gitlab ci/cd Stages
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages


# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

stages:
  - build
  - test
  - coverage

build:cargo:
  stage: build
  script:
    - cd vcst && cargo build

test:cov:
  stage: coverage
  script:
    - rustc --version  # Print version info for debugging
    - cargo --version  # Print version info for debugging
    # install jj VCS, per 20241231 instructions at
    # https://jj-vcs.github.io/jj/latest/install-and-setup/#cargo-binstall
    - cargo install cargo-binstall # dep of jj VCS's isntallation
    - cargo binstall --strategies crate-meta-data jj-cli # install jj VCS
    - cargo binstall --strategies crate-meta-data cargo-llvm-cov # install jj VCS
    - cargo llvm-cov --version  # Print version info for debugging
    - git --version && hg --version && jj --version  # vcst/domain-specific debug info
    # Same as test's steps, but run via code coverage instrumentor:
    - cd vcst && RUSTFLAGS='-D deprecated' cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
    - bash <(curl -s https://codecov.io/bash)

test:cargo:
  stage: test
  script:
    - rustc --version  # Print version info for debugging
    - cargo --version  # Print version info for debugging
    # install jj VCS, per 20241231 instructions at
    # https://jj-vcs.github.io/jj/latest/install-and-setup/#cargo-binstall
    - cargo install cargo-binstall # dep of jj VCS's isntallation
    - cargo binstall --strategies crate-meta-data jj-cli # install jj VCS
    - git --version && hg --version && jj --version  # vcst/domain-specific debug info
    - cd vcst && RUSTFLAGS='-D deprecated' cargo test --locked --all-features --all-targets --workspace --verbose -- --nocapture
