[package]
name = "vcst"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
libvcst = { path = "../lib" }
thiserror = "2.0.9"

[dev-dependencies]
chrono = "0.4.39"
