# TODO: re-enable the whole matrix of rust toolchains once he basics of gitlab's
# ci/cd is being reproduced on github.
name: Build, Docs, Lint, & e2e-Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_cargo:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
         #- beta
         #- nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustc --version  # Print version info for debugging
      - run: cargo --version  # Print version info for debugging
      - run: make build

  test_e2e:
    name: test e2e
    needs: build_cargo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
         #- beta
         #- nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustc --version  # Print version info for debugging
      - run: cargo --version  # Print version info for debugging
      # install jj VCS, per 20241231 instructions at
      # https://jj-vcs.github.io/jj/latest/install-and-setup/#cargo-binstall
      - run: cargo install cargo-binstall # dep of jj VCS's isntallation
      - run: cargo binstall --strategies crate-meta-data jj-cli # install jj VCS
      - run: make test

  test_doc:
    name: rustdoc
    needs: test_e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
         #- beta
         #- nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustc --version  # Print version info for debugging
      - run: cargo --version  # Print version info for debugging
      - run: make doc

  test_lint:
    name: lint
    needs: test_e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
         #- beta
         #- nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustc --version  # Print version info for debugging
      - run: cargo --version  # Print version info for debugging
      - run: rustup component add clippy # install clippy
      - run: cargo clippy --version  # Print version info for debugging
      - run: make lint

  test_cov:
    name: test code-coverage
    needs: test_e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
         #- beta
         #- nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustc --version  # Print version info for debugging
      - run: cargo --version  # Print version info for debugging
      # install jj VCS, per 20241231 instructions at
      # https://jj-vcs.github.io/jj/latest/install-and-setup/#cargo-binstall
      - run: cargo install cargo-binstall # dep of jj VCS's isntallation
      - run: cargo binstall --strategies crate-meta-data jj-cli # install jj VCS
      - run: cargo binstall --strategies crate-meta-data cargo-llvm-cov # install jj VCS
      - run: cargo llvm-cov --version  # Print version info for debugging
      # Same as test's steps, but run via code coverage instrumentor:
      - run: make cov
